### ISSUE TITLE
Whatsapp is not working

### ISSUE THREAD

**Issue by sj-freitas** [ducfilan/Dark-mode-Franz#23]
Hey, I love these dark themes, the Facebook Messenger one works flawlessly.

However, as of 17th April 2020 Whatsapp is not working.

![image](https://user-images.githubusercontent.com/17022606/79577047-02f46700-80bc-11ea-9799-ebd538ac6e48.png)
(The names and images are intentionally censored)

Quotes also look off:
![image](https://user-images.githubusercontent.com/17022606/79577145-2c14f780-80bc-11ea-84b1-f67cacfb4bb3.png)

Thanks!

**Comment by vednoc** [comment]
Hey @ducfilan, I suggest you replace v1 with v2 from here [`wa.user.css`][0] because v1 got deprecated a while ago. There is even a [script][1] to automatically convert it to `darkmode.css` for Franz/Ferdi. 

[0]: https://github.com/vednoc/dark-whatsapp/blob/master/wa.user.css
[1]: https://github.com/vednoc/dark-whatsapp/blob/master/whatsapp.sh

**Comment by ducfilan** [comment]
I updated the whatsapp version. Thank you @vednoc @sj-freitas
